# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_dobot_arm_controller
    - left_dobot_end_effector_controller
    - right_dobot_arm_controller
    - right_dobot_end_effector_controller

  left_dobot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
    action_ns: follow_joint_trajectory
    default: true
  left_dobot_end_effector_controller:
    type: GripperCommand
    joints:
      - left_finger1_joint
    action_ns: gripper_cmd
    default: true
  
  right_dobot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
    action_ns: follow_joint_trajectory
    default: true
  right_dobot_end_effector_controller:
    type: GripperCommand
    joints:
      - right_finger1_joint
    action_ns: gripper_cmd
    default: true