# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_dobot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_dobot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_dobot_end_effector_controller:
      type: position_controllers/GripperActionController

    right_dobot_end_effector_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_dobot_arm_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_dobot_end_effector_controller:
  ros__parameters:
    joint: left_finger1_joint

right_dobot_arm_controller:
  ros__parameters:
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_dobot_end_effector_controller:
  ros__parameters:
    joint: right_finger1_joint